export const FORM_DEFAULT_VALUES = {
  step1: {
    customerType: "individual",
    title: "",
    customerName: "",
    ucName: "",
    fatherName: "",
    dob: "",
    companyName: "",
    primaryPhone: "",
    whatsappSame: "yes",
    whatsappNumber: "",
    contact3: "",
    contact4: "",
    pincode: "",
    country: "",
    state: "",
    city: "",
    locality: "",
    address: "",
    serviceNumber: "",
    localities: [],
  },
  step2: {
    proposalType: "",
    policyType: "",
    receiptNumber: "",
    receiptDate: "",
    vehicleYear: "",
    registrationNumber: "",
    registrationDate: "",
    chassisNumber: "",
    engineNumber: "",
    manufacturingYear: "",
    rtoState: "",
    rtoCity: "",
    product: "",
    manufacturerType: "",
    model: "",
    varience: "",
    fuelType: "",
    products: [],
    manufacturerTypes: [],
    models: [],
    variences: [],
    fuelTypes: [],
    rtoStates: [],
    rtoCities: [],
    rtoStateCities: {},
  },
  step3: {
    previousPolicyAvailable: "no",
    previousPolicyType: "",
    previousInsurer: "",
    insurers: [],
    policyNumber: "",
    previousPolicyStartDate: "",
    previousPolicyEndDate: "",
    odOnlyPolicyStartDate: "",
    odOnlyPolicyEndDate: "",
    tpOnlyPolicyStartDate: "",
    tpOnlyPolicyEndDate: "",
    anyClaim: "no",
    ncb: "",
  },
  step4: {
    newPolicyStartDate: "",
    newPolicyEndDate: "",
    newODPolicyStartDate: "",
    newODPolicyEndDate: "",
    newTPPolicyStartDate: "",
    newTPPolicyEndDate: "",
    newNcb: "",
    brockerName: "",
    newPolicyNumber: "",
    insurerName: "",
    policyIssueDate: "",
    ivd: "",
    addon: [],
    odAmount: "",
    tpAmount: "",
    odTpAmount: "",
    gstAmount: "",
    totalPremiumWithGST: "",
    breakingCharge: "",
    waiverAmount: "",
    brokers: [],
    insurers: [],
    addons: [],
    netPayable: "",
    paCover: "no",
    paCertificateNumber: "",
    paStartDate: "",
    paEndDate: "",
    paCoverAmount: "",
  },
  step5: {
    modeOfInsurancePayment: [],
    cashAmount: "",
    debitCardAmount: "",
    selectedDebitCard: "",
    selectedCreditCard: "",
    selectedPhonePe: "",
    selectedNetBanking: "",
    selectedGooglePay: "",
    creditCardAmount: "",
    dateOfInsurancePayment: "",
    insuranceTransactionId: "",
    totalInsuranceAgencyAmount: "",
    insurancePhonePeAmount: "",
    insuranceNetBankingAmount: "",
    insuranceGoogleAmount: "",
    insuranceNeftAmount: "",
    insuranceChequeAmount: "",
  },
  step6: {
    modeOfCustomerPayment: [],
    paymentReceivedStatus: "",
    dueAmount: "",
    pendingPaymentComments: "",
    paymentClearDate: "",
    customerCashAmount: "",
    customerDebitCardAmount: "",
    customerCreditCardAmount: "",
    customerQrAmount: "",
    dateOfCustomerPayment: "",
    customerTransactionId: "",
    customerChequeAmount: "",
    customerGooglePayAmount: "",
    customerNetBankingAmount: "",
    customerPhonePeAmount: "",
    customerNeftAmount: "",
  },
  step7: {
    callExecutive: [],
    fieldExecutive: [],
    policyUnderwritterExecutive: "",
    pucCertificate: "",
    pucStartDate: "",
    pucEndDate: "",
    remarks: "",
    pucAvailable: "no",
  },
};

export const BROKERS_LIST = [
  "PROBUS - Chitra Chaturvedi",
  "UNITED INDIA - Satya Prakash",
  "POLICY BOSS - Sapna",
  "HOPE BOX - Satya Prakash",
  "TURTLE MINT - Yatendra Kumar",
  "UNIVERSAL SOMPO GENERAL INSURANCE - Yatendra Kumar",
  "RELIANCE GENERAL INSURANCE - Khem Chand",
  "PB PARTNER - Ravi Shankar",
  "PB PARTNER - Shiv Kumar",
  "PB PARTNER - Pavan Chaturvedi",
  "PB PARTNER - Dheeraj Kumar",
  "GIRNAR - Rekha",
  "GIRNAR - Satya Prakash",
  "GOODS INSURANCE BROKRAGE",
  "TATA INSURANCE BROKRAGE - Chitra Chaturvedi",
];

export const INSURERS_LIST = [
  "Acko General Insurance Limited",
  "Bajaj Allianz General Insurance Company Limited",
  "Cholamandalam MS General Insurance Company Limited",
  "Future Generali India Insurance Company Limited",
  "Go Digit General Insurance Limited",
  "HDFC ERGO General Insurance Company Limited",
  "ICICI LOMBARD General Insurance Company Limited",
  "IFFCO TOKIO General Insurance Company Limited",
  "Zurich Kotak General Insurance Company",
  "Liberty General Insurance Limited",
  "Magma General Insurance Limited",
  "National Insurance Company Limited",
  "Raheja QBE General Insurance Co. Ltd.",
  "Reliance General Insurance Company Limited",
  "Royal Sundaram General Insurance Company Limited",
  "SBI General Insurance Company Limited",
  "Shriram General Insurance Company Limited",
  "Tata AIG General Insurance Company Limited",
  "The New India Assurance Company Limited",
  "The Oriental Insurance Company Limited",
  "United India Insurance Company Limited",
  "Universal Sompo General Insurance Company Limited",
  "Zuno General Insurance Ltd",
  "Navi General Insurance Limited",
];

export const ADDONS_LIST = [
  "Zero Depreciation/Nil Depreciation Cover",
  "Engine Protection Cover",
  "No Claim Bonus (NCB) Protection Cover",
  "Roadside Assistance Cover",
  "Return to Invoice Cover",
  "Daily Allowance Cover",
  "Passenger Cover",
  "Consumables Cover",
  "Tyre Protection Cover",
  "Key Loss Protection Cover",
  "Personal Belongings Cover",
  "Personal Accident Cover",
  "Legal Aid",
  "Outstation Emergency Cover",
];

export const MODES = [
  "Cash",
  "Debit Card",
  "Cheque",
  "NEFT/RTGS",
  "Credit Card",
  "PhonePe",
  "Google Pay",
  "Netbanking",
  "QR Code",
];

export const MODS_REQUIRING_UTR = [
  "Cheque",
  "NEFT/RTGS",
  "Credit Card",
  "Google Pay",
  "PhonePe",
  "Netbanking",
  "QR Code",
];

export const PHONEPE_DETAILS = [
  "Yatendra Kumar SBI -7417227114",
  "Yatendra Kumar HDFC -7417227114",
  "Khem chand HDFC -9410075685",
  "Rekha HDFC -9837111044",
  "Chitra CHATURVEDI SBI -7417227114",
  "Chaturvedi Motors HDFC 9837111044",
];

export const DEBIT_CARD_DETAILS = [
  "Chaturvedi Motors - HDFC BANK - C/A",
  "Chaturvedi Motors - SBI BANK - C/A",
  "SatyaPrakash - SBI BANK - S/A",
  "SatyaPrakash - ICICI BANK - S/A",
  "SatyaPrakash - HDFC BANK - S/A",
  "Yatendra Kumar - SBI BANK - S/A",
  "Yatendra Kumar - HDFC BANK - S/A",
  "Khem Chand - HDFC BANK - S/A",
  "Rekha - HDFC BANK - S/A",
  "Chitra - HDFC BANK - S/A",
  "Chitra - SBI BANK - S/A",
  "Sapna - HDFC BANK - S/A",
  "Sapna - SBI BANK - S/A",
  "Sangita - SBI BANK - S/A",
  "Dheeraj - AXIS BANK - S/A",
  "Ravi Shankar - PNB BANK - S/A",
  "Priyanka Sharma - PNB BANK - S/A",
];

export const CREDIT_CARD_DETAILS = [
  "Chaturvedi Motors - HDFC BANK - C/A",
  "Chaturvedi Motors - SBI BANK - C/A",
  "SatyaPrakash - ICICI BANK - S/A",
];

export const NET_BANKING_DETAILS = [
  "Chaturvedi Motors - HDFC BANK - C/A",
  "Chaturvedi Motors - SBI BANK - C/A",
  "SatyaPrakash - SBI BANK - S/A",
  "SatyaPrakash - ICICI BANK - S/A",
  "SatyaPrakash - HDFC BANK - S/A",
  "Yatendra Kumar - SBI BANK - S/A",
  "Yatendra Kumar - HDFC BANK - S/A",
  "Khem Chand - HDFC BANK - S/A",
  "Rekha - HDFC BANK - S/A",
  "Chitra - HDFC BANK - S/A",
  "Chitra - SBI BANK - S/A",
  "Sapna - HDFC BANK - S/A",
  "Sapna - SBI BANK - S/A",
  "Sangita - SBI BANK - S/A",
  "Dheeraj - AXIS BANK - S/A",
  "Ravi Shankar - PNB BANK - S/A",
  "Priyanka Sharma - PNB BANK - S/A",
];

export const FIELD_EXECUTIVES = ["Yashpal Chaudhary", "Self Office"];

export const CALL_EXECUTIVES = [
  "Varsha Singhal",
  "Sarita Kumari",
  "Shilpi shukla",
  "Radha Kumari",
  "Garima Yadav",
  "Tanisha",
  "Anamika chaudhary",
];

export const POLICY_UNDERWRITTER = [
  "Prashant Kumar",
  "Rishik",
  "Sarita Kumari",
  "Varsha Singhal",
  "Shiv Kumar Chaturvedi",
  "Abhishek",
];

export const FUEL_TYPES = [
  "DIESEL",
  "ELECTRIC",
  "PETROL",
  "PETROL HYBRID",
  "CNG/LPG",
];
